spring.application.name=eureka_server
# Server Port
server.port=8761

# Eureka Config
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Optional (clean UI)
eureka.instance.hostname=localhost